on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: deprecated functions
      run: |
        deprecated=true
        if [[ deprecate ]]; then
          echo "::warning::Deprecated function found"
        fi

    - name: Set API key
      run: echo "API_KEY=12345" >> $GITHUB_ENV
    - name: Use API key
      run: echo "Using API Key $API_KEY"

  checking:
    runs-on: ubuntu-latest
    steps:
    - name: Check if a file exist
      run: |
        if [ -f "config.yaml" ]; then
          echo "::debug::config.yaml exists"
        else
          echo "::error::config.yaml is missing"
        fi
