on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - run: |
        deprecated=true
        if [[ deprecate ]]; then
          echo "::warning::Deprecated function found"
        fi
