on:
  workflow_dispatch:

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
    - name: print a message
      run: echo "this job is running"
      if: ${{ github.event_name == 'push' || github.ref == 'refs/head/main' }}
      
      
  
