on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
      
  pull_request:
    branches:
      - main
      - "release/**"    

jobs:
  test:
    runs-on: ubunto-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run tests
        run: npm test